// Products data for CSV export
const productsData = [
  {
    "Codice": "ADV100",
    "Nome prodotto/servizio": "Advertisement",
    "Descrizione": "Budget adv",
    "Categoria": "Content",
    "Prezzo netto": 100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "FLAT500",
    "Nome prodotto/servizio": "Assistenza flat wordpress",
    "Descrizione": "Assistenza prioritaria per interventi evolutivi sito web\n- inserimento nuove funzionalità\n- fixing pagine\n- installazione e verifica plugin\n- clonazione pagine esistenti e inserimento contenuti\n\nNon comprende l'inserimento di software realizzato ad hoc e il design di nuove pagine",
    "Categoria": "Developer",
    "Prezzo netto": 500,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "HOST",
    "Nome prodotto/servizio": "Assistenza server host",
    "Descrizione": "Assitenza sistemistica su hosting venduto a corpo",
    "Categoria": "Consultant",
    "Prezzo netto": 100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "BUD",
    "Nome prodotto/servizio": "Budget concordato",
    "Descrizione": "Budget concordato a livello contrattuale",
    "Categoria": "Developer",
    "Prezzo netto": 1000,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "BUDTRI",
    "Nome prodotto/servizio": "Budget trimestrale concordato",
    "Descrizione": "Ammontare corrisposto a trimestre per l'anno in corso come da contratto di fornitura",
    "Categoria": "Consultant",
    "Prezzo netto": 100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "EML40",
    "Nome prodotto/servizio": "Casella email annuale standard 25G",
    "Descrizione": "Casella email \n- 25 gigabyte\n- webmail\n- smtp\n- imap",
    "Categoria": "Iaas",
    "Prezzo netto": 40,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "caselle",
    "Extra": "",
    "Prezzo di acquisto": 12.0,
    "Giacenza": ""
  },
  {
    "Codice": "WEB80",
    "Nome prodotto/servizio": "Consulenza e sviluppo web continuativo",
    "Descrizione": "",
    "Categoria": "Developer",
    "Prezzo netto": 80,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SEO50",
    "Nome prodotto/servizio": "Consulenza SEO",
    "Descrizione": "Consulenza SEO specifica",
    "Categoria": "Consultant",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "COPY50",
    "Nome prodotto/servizio": "Copywriting pagina web",
    "Descrizione": "Rifinitura e stesura contenuti SEO friendly per pagine web, massimo 1000 battute a pagina",
    "Categoria": "Data insert",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "pagine",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "CPT",
    "Nome prodotto/servizio": "Custom post type",
    "Descrizione": "Implementazione custom post type con Crocoblock",
    "Categoria": "Developer",
    "Prezzo netto": 200,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "post",
    "Extra": "",
    "Prezzo di acquisto": "",
    "Giacenza": ""
  },
  {
    "Codice": "DI50",
    "Nome prodotto/servizio": "Data insert pagine web",
    "Descrizione": "Inserimento contenuti in pagina web",
    "Categoria": "Content",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "pagine",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "DI30",
    "Nome prodotto/servizio": "Data insert prodotti",
    "Descrizione": "Inserimento prodotto da csv o catalogo digitale, con immagini fornite da cliente già ottimizzate",
    "Categoria": "Data insert",
    "Prezzo netto": 30,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "prodotti",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "DES60",
    "Nome prodotto/servizio": "Design e stampa",
    "Descrizione": "Design e messa in stampa esecutivi",
    "Categoria": "Designer",
    "Prezzo netto": 60,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "DID80",
    "Nome prodotto/servizio": "Didattica web",
    "Descrizione": "Didattica singola o di gruppo per utilizzo e gestione piattaforme informatiche e web",
    "Categoria": "Consultant",
    "Prezzo netto": 80,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "MUSDJ",
    "Nome prodotto/servizio": "Dj e intrattenimento",
    "Descrizione": "",
    "Categoria": "Music",
    "Prezzo netto": 80,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "DJSOFT",
    "Nome prodotto/servizio": "Dj e intrattenimento ricevimento",
    "Descrizione": "DJ e intrattenimento soft durante il ricevimento",
    "Categoria": "Music",
    "Prezzo netto": 60,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "ECOM",
    "Nome prodotto/servizio": "Ecommerce update e assistenza mensile",
    "Descrizione": "- Monitoraggio funzionalità e core vitals per sito ecommerce\n- Gestione criticità ecommerce",
    "Categoria": "Monitor",
    "Prezzo netto": 80,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "GEN",
    "Nome prodotto/servizio": "Generico",
    "Descrizione": "Da assegnare",
    "Categoria": "",
    "Prezzo netto": 0,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SOC300",
    "Nome prodotto/servizio": "Gestione canale social",
    "Descrizione": "",
    "Categoria": "Content",
    "Prezzo netto": 300,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "DNS60",
    "Nome prodotto/servizio": "Gestione DNS dominio",
    "Descrizione": "Dominio e gestione DNS Cloudflare\n- acquisto annuale dominio\n- monitoraggio\n- gestione record DNS\n- crisis management",
    "Categoria": "Monitor",
    "Prezzo netto": 60,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "domini",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "PRI",
    "Nome prodotto/servizio": "Gestione privacy sito web standard",
    "Descrizione": "Installazione e monitoraggio codici Iubenda per siti web a medio traffico",
    "Categoria": "Saas",
    "Prezzo netto": 60,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "siti",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "LANGAI50",
    "Nome prodotto/servizio": "Inserimento doppia lingua con traduzione AI",
    "Descrizione": "- configurazione pagine in lingua\n- preparazione contenuti\n- utilizzo servizio IA di traduzione automatica",
    "Categoria": "Saas",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "pagine",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "LAN40",
    "Nome prodotto/servizio": "Inserimento pagina tradotta in lingua",
    "Descrizione": "Inserimento testi pagina lunghezza max 1000 battute, inclusa traduzione automatica",
    "Categoria": "Data insert",
    "Prezzo netto": 40,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "pagine",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "WPI500",
    "Nome prodotto/servizio": "Installazione sito web wordpress base",
    "Descrizione": "Allestimento ed installazione sito web base Wordpress\n- allocazione applicativo in server\n- installazione wordpress\n- installazione e configurazione plugin",
    "Categoria": "Developer",
    "Prezzo netto": 500,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "siti",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "LIC",
    "Nome prodotto/servizio": "Licenza prodotto software",
    "Descrizione": "",
    "Categoria": "Saas",
    "Prezzo netto": 100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "licenze annuali",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "WEB50",
    "Nome prodotto/servizio": "Manutenzione e consulenza web",
    "Descrizione": "Realizzazione, manutenzione e assistenza siti web",
    "Categoria": "Consultant",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "MUSLIVE",
    "Nome prodotto/servizio": "Musica dal vivo",
    "Descrizione": "",
    "Categoria": "Music",
    "Prezzo netto": 100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "NEWS",
    "Nome prodotto/servizio": "News",
    "Descrizione": "- piano editoriale\n- allestimento argomenti in linea con le keyword\n- realizzazione news ottimizzate SEO\n- monitoraggio medio e lungo termine news",
    "Categoria": "Content",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "news",
    "Extra": "Alyce",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SW50",
    "Nome prodotto/servizio": "Plugin o licenze software esterne",
    "Descrizione": "Plugin wordpress esterni o licenze software una tantum",
    "Categoria": "Saas",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "PROJ50",
    "Nome prodotto/servizio": "Project management",
    "Descrizione": "Gestione personale e risorse progetto",
    "Categoria": "Consultant",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SOC20",
    "Nome prodotto/servizio": "Repost su canale social",
    "Descrizione": "Repost su canale social dei contenuti del sito web senza rielaborazioni, prezzo per piattaforma al mese",
    "Categoria": "Content",
    "Prezzo netto": 20,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SCONTO",
    "Nome prodotto/servizio": "Sconto",
    "Descrizione": "Sconto in fattura",
    "Categoria": "Sconti",
    "Prezzo netto": -100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SEOB500",
    "Nome prodotto/servizio": "SEO benchmarking",
    "Descrizione": "Benchmark sito web\n- utilizzo suite di monitoraggio SEO\n- configurazione sito web per audit e benchmarking",
    "Categoria": "Saas",
    "Prezzo netto": 500,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "benchmark",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SEO-S",
    "Nome prodotto/servizio": "SEO strategy",
    "Descrizione": "- SEO strategy\n- keyword match\n- monitoraggio competitor\n- reportistica trimestrale",
    "Categoria": "Content",
    "Prezzo netto": 150,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "Lavoro di Alyce",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SEO-T",
    "Nome prodotto/servizio": "SEO tech",
    "Descrizione": "- monitoraggio analytics\n- monitoraggio search console\n- SEO benchmarking",
    "Categoria": "Saas",
    "Prezzo netto": 150,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SW100",
    "Nome prodotto/servizio": "Server web 100",
    "Descrizione": "Server web 100 medium\n- infrastruttura server\n- gestione ambiente linux\n- backup automatico e on demand\n- crisis management",
    "Categoria": "Iaas",
    "Prezzo netto": 100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 5.0,
    "Giacenza": ""
  },
  {
    "Codice": "SW150",
    "Nome prodotto/servizio": "Server web 150",
    "Descrizione": "Server web 150 large\n- infrastruttura server\n- gestione ambiente linux\n- backup automatico e on demand\n- crisis management",
    "Categoria": "Iaas",
    "Prezzo netto": 150,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 10.0,
    "Giacenza": ""
  },
  {
    "Codice": "SW30",
    "Nome prodotto/servizio": "Server web 30",
    "Descrizione": "Server web 50 standard\n- infrastruttura server\n- gestione ambiente linux\n- backup automatico e on demand\n- crisis management",
    "Categoria": "Iaas",
    "Prezzo netto": 30,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 5.0,
    "Giacenza": ""
  },
  {
    "Codice": "SW50",
    "Nome prodotto/servizio": "Server web 50",
    "Descrizione": "Server web 50 standard\n- infrastruttura server\n- gestione ambiente linux\n- backup automatico e on demand\n- crisis management",
    "Categoria": "Iaas",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 15.0,
    "Giacenza": ""
  },
  {
    "Codice": "SW500",
    "Nome prodotto/servizio": "Server web 500",
    "Descrizione": "Server web 500 medium\n- infrastruttura server\n- gestione ambiente linux\n- backup automatico e on demand\n- crisis management\n- update e monitoraggio wordpress",
    "Categoria": "Iaas",
    "Prezzo netto": 500,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "anni",
    "Extra": "",
    "Prezzo di acquisto": 50.0,
    "Giacenza": ""
  },
  {
    "Codice": "SW20",
    "Nome prodotto/servizio": "Server web small 20",
    "Descrizione": "Server web 20 small\n- infrastruttura server\n- gestione ambiente linux\n- backup automatico e on demand\n- crisis management",
    "Categoria": "Iaas",
    "Prezzo netto": 20,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "mesi",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SERVICE",
    "Nome prodotto/servizio": "Service audio e impianto",
    "Descrizione": "",
    "Categoria": "Music",
    "Prezzo netto": 100,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "postazioni",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SAAS50",
    "Nome prodotto/servizio": "Servizi esterni 50",
    "Descrizione": "Domini o servizi a canone",
    "Categoria": "Saas",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 20.0,
    "Giacenza": ""
  },
  {
    "Codice": "DEV50",
    "Nome prodotto/servizio": "Sviluppo web",
    "Descrizione": "Sviluppo o fixing software web",
    "Categoria": "Developer",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "ore",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "TRA50",
    "Nome prodotto/servizio": "Traferimento sito web presso nostri server",
    "Descrizione": "- trasferimento sito web\n- aggiornamento di sicurezza (ove possibile)",
    "Categoria": "Developer",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "siti",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "EMAILTR30",
    "Nome prodotto/servizio": "Trasferimento casella email",
    "Descrizione": "Trasferimento casella email da provider esistente a Rackspace 25Gb, mantenendo l'archivio email esistente",
    "Categoria": "Saas",
    "Prezzo netto": 30,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "caselle",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "SEC50",
    "Nome prodotto/servizio": "Uptime e security monitor base",
    "Descrizione": "Controllo costante di sicurezza e uptime sito web",
    "Categoria": "Monitor",
    "Prezzo netto": 50,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "WD150",
    "Nome prodotto/servizio": "Web design pagina web",
    "Descrizione": "Realizzazione design pagina web con un giro di correzioni",
    "Categoria": "Designer",
    "Prezzo netto": 150,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "pagine",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "WD200",
    "Nome prodotto/servizio": "Web design pagina web",
    "Descrizione": "Realizzazione design pagina web con un giro di correzioni\n- home\n- about\n- servizi\n- contatti",
    "Categoria": "Designer",
    "Prezzo netto": 200,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "pagine",
    "Extra": "",
    "Prezzo di acquisto": 0.0,
    "Giacenza": ""
  },
  {
    "Codice": "WP200",
    "Nome prodotto/servizio": "Wordpress monitor e update",
    "Descrizione": "Update e monitoraggio Wordpress annuale",
    "Categoria": "Monitor",
    "Prezzo netto": 200,
    "Prezzo lordo": "",
    "Aliquota IVA": "",
    "Descrizione aliquota IVA": "",
    "U.D.M.": "siti",
    "Extra": "",
    "Prezzo di acquisto": 1.0,
    "Giacenza": ""
  }
];

// Make it available globally
window.productsData = productsData;
